
name: SSL check

on:
  schedule:
    - cron: "20 14 * * *"
  workflow_dispatch:

jobs:
  ssl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Kontrollera cert
        run: |
          chmod +x check_ssl.sh
          ./check_ssl.sh
